### ISSUE TITLE
telegraf crashing on probe_alert message

### ISSUE THREAD

**Issue by huttmf** [Apstra/telegraf#10]
It seems like the telegraf server is crashing while trying to process a probe_alert message.

```
admin@aeon-ztps:~/aosom-streaming$ docker logs --tail=30 -f aosomstreaming_telegraf-prom_1
2018-02-09T02:52:11Z D! Output [prometheus_client] wrote batch of 1000 metrics in 86.199099ms
2018-02-09T02:52:11Z D! Output [prometheus_client] wrote batch of 1000 metrics in 102.591975ms
2018-02-09T02:52:11Z D! Output [prometheus_client] wrote batch of 1000 metrics in 177.829772ms
2018-02-09T02:52:11Z D! Output [prometheus_client] wrote batch of 1000 metrics in 82.707514ms
2018-02-09T02:52:11Z D! Output [prometheus_client] wrote batch of 1000 metrics in 83.605069ms
2018-02-09T02:52:12Z D! Output [prometheus_client] wrote batch of 1000 metrics in 119.101731ms
2018-02-09T02:52:12Z D! Output [prometheus_client] wrote batch of 1000 metrics in 94.47376ms
2018-02-09T02:52:12Z D! Output [prometheus_client] wrote batch of 1000 metrics in 110.339015ms
2018-02-09T02:52:12Z D! Output [prometheus_client] wrote batch of 1000 metrics in 112.474632ms
2018-02-09T02:52:13Z D! Output [prometheus_client] wrote batch of 1000 metrics in 78.354873ms
2018-02-09T02:52:13Z D! Output [prometheus_client] wrote batch of 1000 metrics in 113.619087ms
2018-02-09T02:52:13Z D! Output [prometheus_client] wrote batch of 1000 metrics in 96.846689ms
2018-02-09T02:52:13Z D! Output [prometheus_client] wrote batch of 1000 metrics in 87.488222ms
2018-02-09T02:52:13Z D! Output [prometheus_client] wrote batch of 1000 metrics in 104.038989ms
2018-02-09T02:52:13Z D! Output [prometheus_client] wrote batch of 1000 metrics in 74.169102ms
2018-02-09T02:52:15Z D! Output [prometheus_client] buffer fullness: 825 / 10000 metrics.
2018-02-09T02:52:15Z D! Output [prometheus_client] wrote batch of 825 metrics in 73.39639ms
panic: reflect: call of reflect.Value.Interface on zero Value

goroutine 27 [running]:
reflect.valueInterface(0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:936 +0x1bf
reflect.Value.Interface(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:931 +0x44
github.com/influxdata/telegraf/plugins/inputs/aos.(*streamAos).extractAlertData(0xc4200d7fe0, 0x12d65e4, 0xb, 0xc4225706c0, 0x144f880, 0xc42023c5b0, 0x0)
	/home/mike/go-projects/src/github.com/influxdata/telegraf/plugins/inputs/aos/aos.go:107 +0x534
github.com/influxdata/telegraf/plugins/inputs/aos.(*streamAos).msgReader(0xc4200d7fe0, 0x1de4e00, 0xc420066090)
	/home/mike/go-projects/src/github.com/influxdata/telegraf/plugins/inputs/aos/aos.go:510 +0x12fb
created by github.com/influxdata/telegraf/plugins/inputs/aos.(*streamAos).listen
	/home/mike/go-projects/src/github.com/influxdata/telegraf/plugins/inputs/aos/aos.go:46 +0xf1
```

**Comment by Ragsboss** [comment]
Likely the problem is due to `ProbeAlert` having a nested array of structs and `extractAlertData` expects all fields to be of primitive types. We may need special processing for this type of alert..

```
message ProbeAlert {
  optional int64 expected_int = 2;
  optional int64 actual_int = 3;
  optional double expected_float = 4;
  optional double actual_float = 5;
  optional string expected_discrete_state = 6;
  optional string actual_discrete_state = 7;
  required string probe_id = 8;
  required string stage_name = 9;
  repeated KeyValuePair key_value_pairs = 10;
}
```
