### ISSUE TITLE
Panic when query systems in blueprint fails

### ISSUE THREAD

**Issue by Ragsboss** [Apstra/telegraf#5]
Seeing this

```
2018-01-21T13:05:20Z D! Output [influxdb] buffer fullness: 4 / 10000 metrics.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7d77a4]

goroutine 40 [running]:
panic(0xf297e0, 0xc420010040)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/influxdata/telegraf/plugins/inputs/aos/restapi.(*AosServerApi).GetBlueprints(0xc420131100, 0x32, 0xc4207aff68)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/aos/restapi/aosrestapi.go:294 +0x334
github.com/influxdata/telegraf/plugins/inputs/aos.(*Aos).RefreshData(0xc4201da160)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/aos/aos.go:572 +0x57
created by github.com/influxdata/telegraf/plugins/inputs/aos.(*Aos).Start
        /go/src/github.com/influxdata/telegraf/plugins/inputs/aos/aos.go:618 +0x767
```

Due to typo in following code
```
    // Get list of system in the blueprint with Separate Query
    tmp, systemErr := api.GetSystemsInBlueprint(id)
    if err != nil { fmt.Printf("Issue while trying to GetSystemsInBlueprint  %s\n", systemErr ) }

    for y := 0; y < len(tmp.Items); y++ {
      systemId := tmp.Items[y].System.Name
      // fmt.Printf("  System: %s - %s\n", tmp.Items[y].System.Name, tmp.Items[y].System.Role )
      api.Blueprints[id].Systems[systemId] = tmp.Items[y].System
    }
```

The if condition should check `systemErr` instead of `err`.. this is likely the issue

In this case, it’s possible that `GetSystemsInBlueprint` failed and returned a `nil, some-err` and we don’t bail on error and go on to access `tmp` which is nil

**Comment by Ragsboss** [comment]
Created a PR with fix - https://github.com/Apstra/telegraf/pull/6
