### ISSUE TITLE
Panic seen on longevity tests related to concurrency

### ISSUE THREAD

**Issue by Ragsboss** [Apstra/telegraf#7]
Error

```
GetBlueprints() - Id rack-based-blueprint-a6c9f2bc
fatal error: concurrent map read and map write

goroutine 43 [running]:
runtime.throw(0x10a7a0a, 0x21)
    /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc420c7f8b0 sp=0xc420c7f890
runtime.mapaccess1_faststr(0xf1f7a0, 0xc420496ff0, 0xc4209b6c60, 0x1d, 0xc42080e9e0)
    /usr/local/go/src/runtime/hashmap_fast.go:201 +0x4f3 fp=0xc420c7f910 sp=0xc420c7f8b0
github.com/influxdata/telegraf/plugins/inputs/aos.(*streamAos).GetTags(0xc4200e59c0, 0xc42080e960, 0xc, 0x0)
    /go/src/github.com/influxdata/telegraf/plugins/inputs/aos/aos.go:135 +0x1ee fp=0xc420c7fa58 sp=0xc420c7f910
github.com/influxdata/telegraf/plugins/inputs/aos.(*streamAos).msgReader(0xc4200e59c0, 0x16c9dc0, 0xc42001e068)
    /go/src/github.com/influxdata/telegraf/plugins/inputs/aos/aos.go:225 +0x3c4f fp=0xc420c7ff88 sp=0xc420c7fa58
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420c7ff90 sp=0xc420c7ff88
created by github.com/influxdata/telegraf/plugins/inputs/aos.(*streamAos).listen
    /go/src/github.com/influxdata/telegraf/plugins/inputs/aos/aos.go:46 +0x119
```

**Comment by Ragsboss** [comment]
@huttmf saw a similar instance of this even after upgrading Telegraf to latest 1.6

```

GetBlueprints() - Id rack-based-blueprint-a6c9f2bc 
2018-02-05T21:10:30Z D! Finished to Refresh Data, will sleep for 20 sec
fatal error: concurrent map iteration and map write

goroutine 39 [running]:
runtime.throw(0x15aeec8, 0x26)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc420baf7a0 sp=0xc420baf780 pc=0x42bf55
runtime.mapiternext(0xc420baf868)
	/usr/local/go/src/runtime/hashmap.go:778 +0x6f1 fp=0xc420baf838 sp=0xc420baf7a0 pc=0x40a1f1
github.com/influxdata/telegraf/plugins/inputs/aos/restapi.(*AosServerApi).GetSystemByKey(0xc420402080, 0xc420714b40, 0xc, 0xa)
	/home/mike/go-projects/src/github.com/influxdata/telegraf/plugins/inputs/aos/restapi/aosrestapi.go:359 +0xa6 fp=0xc420bafb20 sp=0xc420baf838 pc=0x9281b6
github.com/influxdata/telegraf/plugins/inputs/aos.(*streamAos).GetTags(0xc4200c28c0, 0xc420714b40, 0xc, 0x0)
	/home/mike/go-projects/src/github.com/influxdata/telegraf/plugins/inputs/aos/aos.go:127 +0x126 fp=0xc420bafb90 sp=0xc420bafb20 pc=0x92a8e6
github.com/influxdata/telegraf/plugins/inputs/aos.(*streamAos).msgReader(0xc4200c28c0, 0x1ea8e00, 0xc420116140)
	/home/mike/go-projects/src/github.com/influxdata/telegraf/plugins/inputs/aos/aos.go:225 +0x3d69 fp=0xc420baffc8 sp=0xc420bafb90 pc=0x92eab9
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420baffd0 sp=0xc420baffc8 pc=0x45d221
created by github.com/influxdata/telegraf/plugins/inputs/aos.(*streamAos).listen
	/home/mike/go-projects/src/github.com/influxdata/telegraf/plugins/inputs/aos/aos.go:46 +0xf1```
